--
-- Author: LiQiang
-- Date: 2017-5-9 14:38
--

--[[
    学习cocos2d lua引擎的记录文档
    一个新项目包括
    ./frameworks
    ./res
    ./runtime
    ./src

    还可以有
    ./csrc 加密后code
    ./tools 打包工具
    ./oriRes  打包前资源

    现在主要研究frameworks
    ./cocos2d-x
    build 项目构建
    cmake
    cocos 框架
        2d
            CCAction
            CCActionCamera
            CCActionCatmullRom.cpp
            CCActionCatmullRom.h
            CCActionEase.cpp
            CCActionEase.h
            CCActionGrid.cpp
            CCActionGrid.h
            CCActionGrid3D.cpp
            CCActionGrid3D.h
            CCActionInstant.cpp
            CCActionInstant.h
            CCActionInterval.cpp
            CCActionInterval.h
            CCActionManager.cpp
            CCActionManager.h
            CCActionPageTurn3D.cpp
            CCActionPageTurn3D.h
            CCActionProgressTimer.cpp
            CCActionProgressTimer.h
            CCActionTiledGrid.cpp
            CCActionTiledGrid.h
            CCActionTween.cpp
            CCActionTween.h
            CCAnimation.cpp
            CCAnimation.h
            CCAnimationCache.cpp
            CCAnimationCache.h
            CCAtlasNode.cpp
            CCAtlasNode.h
            CCAutoPolygon.cpp
            CCAutoPolygon.h
            CCCamera.cpp
            CCCamera.h
            CCCameraBackgroundBrush.cpp
            CCCameraBackgroundBrush.h
            CCClippingNode.cpp
            CCClippingNode.h
            CCClippingRectangleNode.cpp
            CCClippingRectangleNode.h
            CCComponent.cpp
            CCComponent.h
            CCComponentContainer.cpp
            CCComponentContainer.h
            CCDrawingPrimitives.cpp
            CCDrawingPrimitives.h
            CCDrawNode.cpp
            CCDrawNode.h
            CCFastTMXLayer.cpp
            CCFastTMXLayer.h
            CCFastTMXTiledMap.cpp
            CCFastTMXTiledMap.h
            CCFont.cpp
            CCFont.h
            CCFontAtlas.cpp
            CCFontAtlas.h
            CCFontAtlasCache.cpp
            CCFontAtlasCache.h
            CCFontCharMap.cpp
            CCFontCharMap.h
            CCFontFNT.cpp
            CCFontFNT.h
            CCFontFreeType.cpp
            CCFontFreeType.h
            CCGLBufferedNode.cpp
            CCGLBufferedNode.h
            CCGrabber.cpp
            CCGrabber.h
            CCGrid.cpp
            CCGrid.h
            CCLabel.cpp
            CCLabel.h
            CCLabelAtlas.cpp
            CCLabelAtlas.h
            CCLabelBMFont.cpp
            CCLabelBMFont.h
            CCLabelTextFormatter.cpp
            CCLabelTextFormatter.h
            CCLabelTTF.cpp
            CCLabelTTF.h
            CCLayer.cpp
            CCLayer.h
            CCLight.cpp
            CCLight.h
            CCMenu.cpp
            CCMenu.h
            CCMenuItem.cpp
            CCMenuItem.h
            CCMotionStreak.cpp
            CCMotionStreak.h
            CCNode.cpp
            CCNode.h
            CCNodeGrid.cpp
            CCNodeGrid.h
            CCParallaxNode.cpp
            CCParallaxNode.h
            CCParticleBatchNode.cpp
            CCParticleBatchNode.h
            CCParticleExamples.cpp
            CCParticleExamples.h
            CCParticleSystem.cpp
            CCParticleSystem.h
            CCParticleSystemQuad.cpp
            CCParticleSystemQuad.h
            CCProgressTimer.cpp
            CCProgressTimer.h
            CCProtectedNode.cpp
            CCProtectedNode.h
            CCRenderTexture.cpp
            CCRenderTexture.h
            CCScene.cpp
            CCScene.h
            CCSprite.cpp
            CCSprite.h
            CCSpriteBatchNode.cpp
            CCSpriteBatchNode.h
            CCSpriteFrame.cpp
            CCSpriteFrame.h
            CCSpriteFrameCache.cpp
            CCSpriteFrameCache.h
            CCTextFieldTTF.cpp
            CCTextFieldTTF.h
            CCTileMapAtlas.cpp
            CCTileMapAtlas.h
            CCTMXLayer.cpp
            CCTMXLayer.h
            CCTMXObjectGroup.cpp
            CCTMXObjectGroup.h
            CCTMXTiledMap.cpp
            CCTMXTiledMap.h
            CCTMXXMLParser.cpp
            CCTMXXMLParser.h
            CCTransition.cpp
            CCTransition.h
            CCTransitionPageTurn.cpp
            CCTransitionPageTurn.h
            CCTransitionProgress.cpp
            CCTransitionProgress.h
            CCTweenFunction.cpp
            CCTweenFunction.h
            CMakeLists.txt
            cocos2d_headers.props
            cocos2d.def
            cocos2dx.props
            libcocos2d_8_1
            libcocos2d_win10
            libcocos2d.vcxproj
            libcocos2d.vcxproj.filters
            win10_props
            winrt_8.1_props
            wp_8.1_props
    extensions
    external
    licenses
    plugin
    tools
    ./runtime-src
]]
